apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kurban-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # Panggil middleware rate-limit yang kita buat di 04-middleware.yaml
    traefik.ingress.kubernetes.io/router.middlewares: default-kurban-ratelimit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kurban-app-svc
            port:
              number: 80