apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kurban-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Batasi request maksimal 5 request per detik per IP
    nginx.ingress.kubernetes.io/limit-rps: "5"
    # Saat limit terlampaui, alihkan (burst limit) atau beri respon rate-limit
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kurban-app-svc
            port:
              number: 80